#!/usr/bin/env python3
"""Generate the EPYC llama readiness document index."""
from __future__ import annotations

import argparse
from pathlib import Path


DEFAULT_OUTPUT = Path("docs/epyc-llama-readiness-generated.md")


def _rel(path: Path, root: Path) -> str:
    return str(path.relative_to(root))


def _find_docs(root: Path) -> list[Path]:
    docs = [
        path
        for path in (root / "docs").rglob("*.md")
        if path.name != DEFAULT_OUTPUT.name and "build" not in path.parts
    ]
    keep = [
        path
        for path in docs
        if path.name in {"epyc-llama-readiness-index.md", "build.md", "install.md", "speculative.md"}
        or "development" in path.parts
        or "backend" in path.parts
    ]
    return sorted(keep, key=lambda path: _rel(path, root))


def render(root: Path) -> str:
    lines = [
        "# EPYC llama Generated Readiness Docs Index",
        "",
        "Generated by: `scripts/docs/generate_readiness_docs_index.py`",
        "",
        "This index is generated from repository documentation sources and is used as the",
        "L4 generated-docs surface for the experimental v7 llama.cpp worktree.",
        "",
        "## Core Readiness Documents",
        "",
    ]
    for path in _find_docs(root):
        rel = _rel(path, root)
        title = path.read_text(encoding="utf-8", errors="replace").splitlines()
        heading = next((line.lstrip("# ").strip() for line in title if line.startswith("#")), path.stem)
        lines.append(f"- [{heading}](../{rel}) - `{rel}`")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    root = Path.cwd()
    output = Path(args.output)
    if not output.is_absolute():
        output = root / output
    text = render(root)
    if args.check:
        current = output.read_text(encoding="utf-8") if output.exists() else ""
        if current != text:
            print(f"{output}: stale")
            return 1
        print(f"{output}: up to date")
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text, encoding="utf-8")
    print(f"wrote {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
