#!/usr/bin/env python3
"""Generate an index of local analysis/reporting surfaces."""
from __future__ import annotations

import argparse
from pathlib import Path


DEFAULT_OUTPUT = Path("docs/epyc-llama-analysis-reports.md")
REPORT_PATTERNS = (
    "scripts/compare-*.py",
    "scripts/*bench*.py",
    "scripts/*bench*.sh",
    "scripts/hip/*.py",
    "tools/parser/template-analysis.cpp",
    "docs/ops/*.csv",
)


def _rel(path: Path, root: Path) -> str:
    return str(path.relative_to(root))


def _collect(root: Path) -> list[Path]:
    paths: list[Path] = []
    for pattern in REPORT_PATTERNS:
        paths.extend(root.glob(pattern))
    return sorted({path for path in paths if path.exists() and path.is_file()}, key=lambda p: _rel(p, root))


def render(root: Path) -> str:
    lines = [
        "# EPYC llama Analysis Reports Index",
        "",
        "Generated by: `scripts/analysis/generate_analysis_reports_index.py`",
        "",
        "This file inventories local report generators and static report inputs used",
        "for L4 analysis-report readiness.",
        "",
        "## Report Surfaces",
        "",
    ]
    for path in _collect(root):
        lines.append(f"- `{_rel(path, root)}`")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    root = Path.cwd()
    output = Path(args.output)
    if not output.is_absolute():
        output = root / output
    text = render(root)
    if args.check:
        current = output.read_text(encoding="utf-8") if output.exists() else ""
        if current != text:
            print(f"{output}: stale")
            return 1
        print(f"{output}: up to date")
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text, encoding="utf-8")
    print(f"wrote {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
