#!/usr/bin/env python3
"""Generate a replay-analysis packet from existing comparison surfaces."""
from __future__ import annotations

import argparse
import subprocess
from pathlib import Path


DEFAULT_OUTPUT = Path("docs/epyc-llama-replay-analysis.md")


def _git(root: Path, args: list[str]) -> str:
    proc = subprocess.run(["git", *args], cwd=root, check=False, text=True, capture_output=True)
    if proc.returncode != 0:
        return ""
    return proc.stdout.strip()


def render(root: Path, base: str) -> str:
    changed = _git(root, ["diff", "--name-only", base, "--"])
    recent = _git(root, ["log", "--oneline", "-10", "--", "scripts", "docs", "tools"])
    lines = [
        "# EPYC llama Replay Analysis",
        "",
        "Generated by: `scripts/analysis/replay_analysis.py`",
        f"Base ref: `{base}`",
        "",
        "This packet supports L4 replay-analysis readiness by summarizing existing",
        "comparison and benchmark surfaces without rerunning model inference.",
        "",
        "## Available Replay Inputs",
        "",
        "- `scripts/compare-commits.sh`",
        "- `scripts/compare-llama-bench.py`",
        "- `scripts/compare-logprobs.py`",
        "- `scripts/server-bench.py`",
        "",
        "## Changed Files Since Base",
        "",
    ]
    if changed:
        lines.extend(f"- `{line}`" for line in changed.splitlines())
    else:
        lines.append("- No tracked changes against base.")
    lines.extend(["", "## Recent Analysis-Relevant Commits", ""])
    if recent:
        lines.extend(f"- `{line}`" for line in recent.splitlines())
    else:
        lines.append("- No recent matching commits.")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base", default="HEAD")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    root = Path.cwd()
    output = Path(args.output)
    if not output.is_absolute():
        output = root / output
    text = render(root, args.base)
    if args.check:
        current = output.read_text(encoding="utf-8") if output.exists() else ""
        if current != text:
            print(f"{output}: stale")
            return 1
        print(f"{output}: up to date")
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text, encoding="utf-8")
    print(f"wrote {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
