#!/usr/bin/env python3
"""Generate a lightweight security-audit checklist for this tree."""
from __future__ import annotations

import argparse
from pathlib import Path


DEFAULT_OUTPUT = Path("docs/epyc-llama-security-audit.md")
EVIDENCE = (
    "SECURITY.md",
    "tools/server/README-dev.md",
    "tools/server/tests/unit/test_security.py",
    ".github/workflows/server.yml",
)


def render(root: Path) -> str:
    lines = [
        "# EPYC llama Security Audit",
        "",
        "Generated by: `scripts/security_audit.py`",
        "",
        "This checklist maps existing llama.cpp security surfaces to the EPYC L4",
        "security-audit readiness criterion.",
        "",
        "## Evidence",
        "",
    ]
    for raw in EVIDENCE:
        path = root / raw
        state = "present" if path.exists() else "missing"
        lines.append(f"- `{raw}` - {state}")
    lines.extend(
        [
            "",
            "## Review Checklist",
            "",
            "- [ ] Re-run server security tests before promoting an experimental kernel.",
            "- [ ] Review server file-access and public-endpoint boundaries after API changes.",
            "- [ ] Confirm no secrets, private model paths, or host-only tokens are committed.",
            "- [ ] Record any accepted risk in the promotion packet.",
            "",
        ]
    )
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    root = Path.cwd()
    output = Path(args.output)
    if not output.is_absolute():
        output = root / output
    text = render(root)
    if args.check:
        current = output.read_text(encoding="utf-8") if output.exists() else ""
        if current != text:
            print(f"{output}: stale")
            return 1
        print(f"{output}: up to date")
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text, encoding="utf-8")
    print(f"wrote {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
